language: java
jdk: oraclejdk8

services:
  - mysql
  
cache:
  directories:
    - node_modules
    - $HOME/.m2
  
before_install:
  - npm install 
  - mysql -e 'CREATE DATABASE usersDB;'
  
script: 
  - mvn verify site
  
notifications:
  email:
    - lam@cphbusiness.dk

after_success:
  - surge --project ./target/site --domain x123.surge.sh
after_failure:
  #Site folder is not created for failing tests, this will create a site Without test reports
  - mvn clean test jacoco:report coveralls:report
  - surge --project ./target/site --domain x123.surge.sh
