language: java
jdk: oraclejdk8

services:
  - mysql
  
cache:
  directories:
    - node_modules
    - $HOME/.m2
  
before_install:
  - npm install 
  - mysql -e 'CREATE DATABASE usersDB;'
  
script: 
  - mvn verify site
  ##- mvn site
  
notifications:
  email:
    - lam@cphbusiness.dk

after_success:
  ##- mvn clean test jacoco:report coveralls:report
 ## - mvn verify site
  - surge --project ./target/site --domain x123.surge.sh
